name: Run frontend tests
on: [push]
jobs:
  run-frontend-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - run: npm ci
      - run: npm run prettier:check
      - run: npm run typecheck
